PostApp/urls.py
from django.urls import path

from . import views

urlpatterns = [path('',views.index,name='index'),
                path('add_post/',views.add_post,name='add_post'),
                path('delete_post/<int:pk>/',views.delete_post,name='delete_post'),
                path('delete_com/',views.delete_com,name='delete_com'),
                path('about_me/',views.about_me,name='about_me'),

                path('profile/<int:pk>',views.profile,name='profile'),

                path('dashboard/',views.Dashboard.as_view(),name = 'dashboard'),
                path('test/',views.test,name = 'test'),

                path('login/',views.loginPage,name = 'login'),
                path('register/',views.registerPage,name = 'register'),
                path('logout',views.logoutUser,name = 'logout')
]

porfolio/urls.py
from django.contrib import admin
from django.urls import path,include

# nie uzywac w produkcji (zdjecia beda trzymane inaczej)
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('PostApp.urls')),
    path('admin/', admin.site.urls),
] 

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PostApp/models.py
from typing import ForwardRef
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Pseudo_User(models.Model):
    user = ForeignKey(User,on_delete=CASCADE,null=True)
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    nickname = models.CharField(max_length=50)
    profile_img = models.ImageField(null = True, blank = True)

    def __str__(self) -> str:
        return self.name +' '+ self.surname + ' "' + self.nickname + '"' 

        

class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE ,null=True)
    pub_date = models.DateTimeField(default=timezone.now,null=True)
    content = RichTextField(blank=True,null=True)
    # content = models.CharField(max_length=200,null=True)

    def __str__(self) -> str:
        return 'post'


class Post_comments(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,blank=True,null=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE ,blank=True,null=True)
    content = RichTextField(blank=True,null=True)
    # content = models.TextField( max_length=200 ,blank=True,null=True)
    pub_date = models.DateTimeField(default=timezone.now,null=True)
    def __str__(self) -> str:
        return ' Comment '

class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE,  )
    profile_image = models.ImageField(null=True,blank = True)
    name =  models.CharField(max_length=100,null=True,blank = True)
    surname = models.CharField(max_length=100,null=True,blank = True)
    nickname = models.CharField(max_length=100,null=True,blank = True)
    email = models.CharField(max_length=100 ,null=True,blank = True)

    def __str__(self) -> str:
        return 'Profile'

PostApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import fields
from django.forms import ModelForm,Form
from django.http import request
from .models import *

from django.utils import timezone
from ckeditor.widgets import CKEditorWidget

class PostForm(ModelForm):
    # content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post
        fields = '__all__'
        widgets =  {
        'author' : forms.HiddenInput(),
        'pub_date':forms.HiddenInput(),
        'content' :forms.CharField(widget=CKEditorWidget()),
        }

class MyForm(Form):
    author = forms.CharField(label = 'Nazwa użytkowania: ',max_length=100, widget=forms.HiddenInput())
    pub_date = forms.DateTimeField(label = 'Data publikacji: ',widget=forms.HiddenInput()) 
    content = forms.CharField(label = 'Treść: ',max_length=200)

class CommentForm(ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post_comments
        fields = '__all__'
        widgets =  {
        # 'post': forms.HiddenInput(),
        'author' : forms.HiddenInput(),
        'pub_date':forms.HiddenInput(),
        }
        
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        # fields = '__all__'

class ProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = '__all__'
        exclude = ['user']

PostApp/views.py
from django.forms.widgets import HiddenInput
from django.http.request import QueryDict
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView,DetailView,UpdateView,FormView,ListView

from django.forms import inlineformset_factory

from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

from .models import *
from django.contrib.auth.models import User
from .forms import *
# Create your views here.

#class-based views

#generic-class-based views
class Dashboard(TemplateView):
    template_name = 'PostApp/dashboard.html'
    model = Post
    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex['posts'] = Post.objects.all()
        contex['comments'] = Post_comments.objects.all()
        return contex

    def get(self,request,*args,**kwargs):
        posts = Post.objects.all()
        contex = {'posts':posts}
        return render(request,'PostApp/dashboard.html',contex)

    def post(self,request):
        # Post.objects.create()
        pass

# function-based views

@login_required(login_url='login')
def index(request): 
    author = User.objects.get(username = request.user)
    form = PostForm(initial={'author': author,'pub_date' : timezone.now})
    commentForm = CommentForm(initial={'author': author,'pub_hour' : timezone.now})

    if request.method == 'POST':
        if request.POST.get('form_type') == 'add_post':
            form = PostForm(request.POST)
            print(request.POST)
            if form.is_valid():
                form.save()
                #jesli chce wrocic do innej strony
                return redirect("/")
        elif request.POST.get('form_type') == 'add_comm':
            commentForm = CommentForm(request.POST)
            print(request.POST)
            if commentForm.is_valid():
                commentForm.save()
                return redirect('/')

    posts = Post.objects.all()
    contex = {'posts' : posts,'form':form,'commentForm':commentForm}

    return render(request,'PostApp/index.html',contex)

def test(request):
    form =  MyForm(initial={'author' : request.user})
    print(request.POST)
    contex = {'form':form}
    return render(request,'PostApp/test.html',contex)

# def add_comment(request):
#     form = Post_commForm()
#     if request.method == 'POST':
#         form =  Post_commForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('/')

#     comments = Post_comments.objects.all()
#     contex ={'form_com':form,'comments':comments, 'my_number' : 123}
#     return render(request,'PostApp/comment_section.html',contex)

@login_required(login_url='login')
def add_post(request):
    form = PostForm()
    Post.objects.get(request)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
            
    contex = {'form':form}
    return render(request,'PostApp/add_post.html',contex)
    
@login_required(login_url='login')
def delete_post(request,pk):
    del_post = Post.objects.get(id=pk)

    if request.method == 'POST':
        del_post.delete()
        return redirect("/")

    contex = {'post':del_post}
    return render(request,'PostApp/delete_post.html',contex)

@login_required(login_url='login')
def delete_com(request):
    pass



def about_me(requset):
    return render(requset,'PostApp/about_me.html')

def profile(request,pk):
    # user = UserProfile.objects.get_or_create(user_id = pk)
    user =  request.user.userprofile
    form = ProfileForm(instance=user)
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            form.save()

    contex = {'profile':profile,'form':form}

    return render(request,'PostApp/profile.html',contex)

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        form =  CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            print(request.POST)
            if form.is_valid():
                print('po valid')
                form.save()
                username = form.cleaned_data.get('username')
                messages.success(request,'Account was created for ' + username)
                return redirect('login')

        contex = {'form':form}
        return render(request,'PostApp/register.html',contex)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        if request.method == 'POST':
            username=request.POST.get('username')
            password=request.POST.get('password')
            
            user = authenticate(request,username = username , password = password)
            if user is not None:
                login(request,user)
                return redirect('index')
            else:
                messages.info(request,'Username OR password is incorrect')

        contex = {}
        return render(request,'PostApp/login.html',contex)

def logoutUser(request):
    logout(request)
    return redirect('login')

PostApp/templates/PostApp/about_me.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>O mnie</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    {%extends 'PostApp/site_temp.html'%}
</head>
<body>
    {%block content%}
    <div class = 'container-fluid'>
        <div class = 'row'>
            <div class = 'col m-3'>
                <div class = 'border border-outline-dark m-3'>
                    <img class = 'img-thumbnail p-3' style="max-block-size: fit-content;" src="https://www.tapeciarnia.pl/tapety/normalne/132863_szaro_bury_kot.jpg" alt="kot">
                    <a class = 'text-center' href="https://www.linkedin.com/">
                        <h1><i class="bi-github" role="img" aria-label="GitHub"></i></h1>
                    </a>
                </div>
                <div class = 'border border-outline-dark m-3'>
                    <p>faysgiuahfuha</p>
                </div>
            </div>
            <div class = 'col m-3'>
                <div class = 'border p-3 m-3'>
                    <h4>O mnie</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore sed quod deserunt ea 
                        praesentium ex, quaerat sequi? Esse reprehenderit in corporis. 
                        Iure, amet molestiae. Obcaecati, aperiam. Maxime repellendus maiores sapiente!</p>

                </div>
                <div class = 'border m-3 p-3'>
                    <ul>
                        <p>Wykształcenie</p>
                        <li>asd</li>
                        <li>asd</li>
                        <li>asd</li>
                    </ul>
                </div>
                <div class = 'border m-3 p-3'>
                    <ul>
                        <p>Doświadczenie</p>
                        <li>asd</li>
                        <li>asd</li>
                        <li>asd</li>
                    </ul>
                </div>
                <div class = 'border m-3 p-3'>
                    <ul>
                        <p>Umiejętności</p>
                        <li>asd</li>
                        <li>asd</li>
                        <li>asd</li>
                    </ul>
                </div>

                <div class = 'border m-3 p-3'>
                    <ul>
                        <p>Zainteresowania</p>
                        <li>asd</li>
                        <li>asd</li>
                        <li>asd</li>
                    </ul>
                </div>
            </div>
        </div>



    </div>
    {%endblock%}
</body>
</html>

PostApp/templates/PostApp/add_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add post</title>
</head>
<body>
    
    <div>
        <form action="index.html/", method="POST">
            {%csrf_token%}
            {{form}}
            <input type="submit" name="Submit">
        </form>
    </div>

</body>
</html>

PostApp/templates/PostApp/comment_section.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comment section</title>
</head>
<body > 
    <div class = 'd-flex justify-content-center '>
        <form action="" method="POST">
            {% csrf_token %}
            {{form_com}}
            <input class = 'mx-3' type="submit" name="Add_comment" value="Dodaj">
        </form>
    
        <div class="card m-3 " style="width: 25rem;">
        <ul class="list-group list-group-flush m-3 border">
            {%for comm in comments%}
            <li class="list-group-item ">{{comm.content}}</li>
            {%endfor%}
        </ul>
        </div>
    </div>
</body>
</html>

PostApp/templates/PostApp/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <h5>Witaj na stronie Dashboard</h5>
    
    {%for post in posts%}
        <p>{{post.content}}</p>
        {%for comm in comments %}
            <p>comm.content</p>
        {%endfor%}
    {%endfor%}

</body>
</html>

PostApp/templates/PostApp/delete_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Usuwanie posta</title>

    {%extends 'PostApp/site_temp.html'%}
</head>

<body>
        {%block content%}
            <div class= 'd-flex justify-content-center'>
                    <form action="{% url 'delete_post' post.id%}" method="POST" class = 'card  border-danger   p-3 m-3 w-25'>
                        {%csrf_token%}
                        <p style = 'font-size: larger;'>Czy chcesz usunąć post ?</p>
                        <a href="{%url 'index'%}" class = 'btn btn-lg btn-primary m-3'>Wróć</a>
                
                        <input type="submit" name="Confirm" value="Usuń" class = 'btn btn-lg btn-danger m-3'>
                
                    </form>
            </div>
            {%endblock%}
</body>
</html>

PostApp/templates/PostApp/htmlTest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div style="display: flex; height: 100vh; padding: 0.5%;">
        <div style="padding: 1em; background-color: rgb(10, 10, 92); margin: 0.5%;">
            <div style=" height: 200px; width: 200; background-color: rgb(255, 255, 255);">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis beatae quasi iste dolorem, perferendis excepturi earum exercitationem sequi labore! Doloremque neque voluptatem amet laudantium incidunt explicabo fugit ducimus officiis quod.</p>
            </div>
        </div>
        <div style="padding: 1em; background-color: rgb(88, 88, 179); margin: 0.5%;">
            <div style="background-color: rgb(255, 255, 255); size: 1em;">
                <p>Hello</p>
            </div>
        </div>
    </div>

</body>
</html>

PostApp/templates/PostApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Strona główna</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {%extends 'PostApp/site_temp.html'%}
</head>
<body>

{%block content%}

    <div class = 'container-flex'>
 

        <div class = 'row justify-content-md-center'>

            <div class = ' card-column  w-50 '>
                <div class="row ">
                    <p class= "">
                        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                        Dodaj posta
                        </button>
                    </p>
                    <div class="collapse" id="collapseExample">
                        <div class="card p-3 m-3 " >
                            <form action="" method="POST" class = 'mx-auto'>
                                {% csrf_token %}
                                {{ form.media }}
                                {{ form.as_p }}
                                <input type="hidden" name="form_type", value="add_post">
                                <input type="submit" name="Submit" value="Dodaj" class = 'btn btn-primary mb-3 ' >
                            </form> 
                        </div>
                    </div>
                </div>
                
                <!-- <div class="card p-3 m-3 " >
                    
                    <form action="" method="POST" class = 'mx-auto'>
                        {% csrf_token %}
                        {{ form.media }}
                        {{ form.as_p }}
                        <input type="hidden" name="form_type", value="add_post">
                        <input type="submit" name="Submit" value="Dodaj" class = 'btn btn-primary mb-3 ' >
                    </form> 
                </div> -->

                
                {%for post in posts%}
                    <div class="container" style="margin-bottom: 3rem;
                                            border-width: 5px;
                                            border-style: solid;
                                            border-color: rgb(96, 104, 104);
                                            padding: 1em;
                                            border-radius: 2%;
                                            background-color: #434a52;
                                            box-shadow: 0px 10px 10px 0px rgb(163, 163, 163), 0px 10px 10px 0px rgb(163, 163, 163);">

                        <div class=" rounded mb-1" >
                            <div class="bg-light rounded">
                                <div class = 'card-header'>
                                    <div class=" row align-items-center ">
                                            <div class="w-10  align-items-center " >
                                                    <img src="{{post.author.userprofile.profile_image.url}}"
                                                     alt="profile picture" style="height: 5em; border-radius: 50%;">
                                            </div>
                                            <div class="w-75  align-items-center ">
                                                <h4 class="card-title">{{post.author.userprofile.name}} {{post.author.userprofile.surname}}</h4>
                                                <h6 class="card-subtitle mb-2 text-muted">#{{post.author.userprofile.nickname}}</h6>
                                            </div>
                                            <div class=" align-items-end" >
                                                <a href="{%url 'delete_post' post.id%}" class="btn-sm btn-primary">Usuń</a>
                                            </div>
                                    </div>
                                </div>
                                <div class = 'card card-body h-75'>
                                    {{post.content | safe}}
                                </div>
                            </div>
                        </div>
 
                        {%for comment in post.post_comments_set.all%}
                        <div class ="p-1 mb-1 rounded" style="background-color: #69727c;">
                            <div class = 'card mb-1'>
                                <h4 class="card-title">{{comment.author.userprofile.name}} {{comment.author.userprofile.surname}}</h4>
                                <h6 class="card-subtitle mb-2 text-muted">#{{comment.author.userprofile.nickname}}</h6>
                            </div>
                            <div class = 'card' style="size: 1em;">
                                <p style="size: 1em;"> {{comment.content | safe}} </p>
                            </div>
                        </div>
                        {%endfor%}
                    </div>
                {%endfor%}
                </div>
            </div>
        </div>
    </div>

{%endblock%}


</html>

PostApp/templates/PostApp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>

<body>

    <div class = 'container-fluid m-5 p-5 text-center'>
        <div class = 'row'>
            
            <div class = 'col'>
            </div>

            <div class = 'col'>
                <div class = 'border border-dark rounded p-3'>
                    <h3>Logowanie</h3>
                    <form action="" method="POST">
                        {%csrf_token%}
                        <input type="text" name='username' class = 'm-3 rounded text-center' placeholder="Username"> <br>
                        <input type="password" name='password' class = 'm-3 rounded text-center' placeholder="Password"> <br>
                        <input type="submit" name="login" value="Login" class = 'btn btn-primary m-3'> <br>
                    </form>
                    {%for message in messages%}
                        <p id= 'messages'> {{message}} </p>
                    {%endfor%}

                    <a href="{%url 'register'%}">Utwórz nowe konto</a>
                </div>
            </div>

            <div class = 'col'>
            </div>

        </div>
        </div>
       
</body>

</html>

PostApp/templates/PostApp/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    {%extends 'PostApp/site_temp.html'%}
</head>
<body>
    {% load static %}

    {%block content%}

        <div class = 'row'>
            <div class= 'col-md-3'>
                <div class = 'card card-body'>
                    <img src="{{request.user.userprofile.profile_image.url}}" alt="zdjecie profilowe">
                </div>
            </div>
            <div class = 'col-md-9'>
                <div class = 'card card-body'>
                    <form action="" method="POST" class="form-floating" enctype="multipart/form-data">
                        {%csrf_token%}
                        {{form.as_p}}
                        <input type="submit" class="btn btn-primary" name = 'update_profile'>
                    </form>
                </div>
            </div>
        </div>

    {%endblock%}
</body>
</html>

PostApp/templates/PostApp/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stwórz konto</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <div class = 'container-fluid m-5 p-5'>
        <div class = 'row'>
            <div class = 'col'></div>
            <div class = 'col border border-dark text-center w-75 rounded '>
                <form action="" method="POST">
                    <h3>Rejestracja</h3>
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" name="create_user" class = 'btn btn-primary m-3' value="Stwórz">
                </form>
            </div>
            <div class = 'col'></div>
        </div>
    </div>
</body>
</html>

PostApp/templates/PostApp/site_temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
</head>


<body class= 'bg-light'>
    <div class ='container-fluid mb-3'>
        <div class = 'row bg-dark justify-content-between '>
            <div class="d-flex justify-content-start">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <!-- Pierwszy element na pasku -->
                    <div class="container-fluid ">
                      <a class="navbar-brand " href="#">Adam Stępień</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
    
                      <!-- Kolejne elementy na pasku -->
                      <div class="collapse navbar-collapse " id="navbarText">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{%url 'about_me' %}">O mnie</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{%url 'index'%}">Aplikcja 1</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{%url 'test'%}">Aplikcja testowa</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{%url 'profile' request.user.id %}">Aplikcja testowa</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </nav>
            </div>

              <style>
                .footer{
                  font-size: 18px;
                  color: #fff;
                  margin-right: 20px;
                  padding: 10px;
                }
              </style>

            <div class="d-flex justify-content-end align-items-center">
              <!-- <a href="{%url 'login'%}" class = 'btn btn-primary m-3 '>Login</a> -->
              <span class = 'footer'> Hello, {{request.user}} </span>
              <span class = 'footer'><a class="btn btn-primary" href="{%url 'logout'%}">Logout</a></span>
            </div>
        </div>


    </div>

      {%block content%} 

      {%endblock%}

    <style class = 'footer'>
      footer
      {
        box-sizing: content-box;
        display: block ;
        z-index: auto;
        position: static;
        background-color: #343a40;

      }
      h5
      {
        font-size: 3vh;
        color: white;
        text-align: center;
      }
    </style>

    <div class="m-5"></div>
      <footer class="fixed-bottom">
        <h5 class = 'font-lg'> Stopka</h5>
      </footer>
      
</body>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>